// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfjl6IW6AkDpmfuhi2Xp62PXcIBni5jl0',
    appId: '1:62844654128:android:258a6a0421e1cd2f8053f5',
    messagingSenderId: '62844654128',
    projectId: 'ecom-store-acde3',
    storageBucket: 'ecom-store-acde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTWaELblNbPOiuzOLidFUfQlX44k4ff2k',
    appId: '1:62844654128:ios:bb8d40ac2171043c8053f5',
    messagingSenderId: '62844654128',
    projectId: 'ecom-store-acde3',
    storageBucket: 'ecom-store-acde3.firebasestorage.app',
    iosBundleId: 'com.example.day28',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFHcPChZtmpnh_fN-7AdIotcLJyGeqYI',
    appId: '1:62844654128:web:077002a4fd82b2d18053f5',
    messagingSenderId: '62844654128',
    projectId: 'ecom-store-acde3',
    authDomain: 'ecom-store-acde3.firebaseapp.com',
    storageBucket: 'ecom-store-acde3.firebasestorage.app',
    measurementId: 'G-1H5WNNQPKF',
  );

}